[project]
name = "youth-mental-health-runtime"
channels = ["nvidia", "conda-forge", "pytorch", "xformers"]
platforms = ["linux-64"]

[dependencies]

# BASE DEPENDENCIES
[feature.base]
[feature.base.host-dependencies]
gcc = "*"
gxx = "*"
binutils = "*"
llvm-openmp = "*"
compilers = "*"

[feature.base.activation]
scripts = [
    'export CMAKE_AR="$(which ar)"',
    'export CMAKE_ARGS="-DCMAKE_C_FLAGS=-fopenmp -DCMAKE_CXX_FLAGS=-fopenmp"'
]

[feature.base.dependencies]
accelerate = "0.33.0"
einops = "0.8.0"
jsonpickle = "3.2.2"
langchain = "0.3.3"
langchain-community = "0.3.2"
loguru = "0.7.*"
nltk = "3.9.1"
numba = "0.60.*"
numpy = "1.26.4"
pandas = "2.2.2"
peft = "0.12.0"
pip = "24.2"
pytest = "8.3.*"
python = "3.10.14"
pytorch-lightning = "2.4.0"
scikit-learn = "1.5.1"
scipy = "1.14.1"
sentencepiece = "0.2.0"
spacy = "3.7.5"
tqdm = "4.66.*"
transformers = "4.44.2"
sentence-transformers = "2.0.0"
xgboost = "2.1.1"

# CPU DEPENDENCIES
[feature.cpu]
[feature.cpu.dependencies]
cpuonly = {channel = "pytorch"} # PyTorch metapackage for CPU-only
pytorch = {version = "2.1.2", channel = "pytorch"}

[feature.cpu.pypi-dependencies]
llama-cpp-python = { version = "==0.3.1" }

# GPU DEPENDENCIES
[feature.gpu]
system-requirements = {cuda = "11.8"}
[feature.gpu.activation]
scripts = [
    'export CMAKE_ARGS="-DGGML_CUDA=on -DCMAKE_C_FLAGS=-fopenmp -DCMAKE_CXX_FLAGS=-fopenmp"',
    'export FORCE_CMAKE="1"'
]
[feature.gpu.dependencies]
bitsandbytes = { version = "0.43.3", build="cuda118_py310hda4ad70_1" }
cudatoolkit = {version = "11.8", channel = "conda-forge"}
cuda-cudart = {version = "11.8.*", channel = "nvidia"}
cuda-version = {version = "11.8", channel = "conda-forge"}
cudnn = {version = "*", channel = "conda-forge"}
cupy = {version = "12.*"}
pytorch = {version = "2.1.2", channel = "pytorch"}
pytorch-cuda = {version = "11.8", channel = "pytorch"} # PyTorch metapackage for cuda version
xformers = {version = "0.0.23.post1", channel = "xformers"}

[feature.gpu.pypi-dependencies]
llama-cpp-python = { version="==0.3.1" }

[environments]
cpu = { features = ["base", "cpu"]}
gpu = { features = ["base", "gpu"]}
